#!/usr/bin/env node
/**
 * Assemble a deployable Apps Script project for one environment.
 *
 *   node scripts/build.js dev|prod [--separate]
 *
 * Writes dist/<env>/ containing:
 *   - Code.gs         all *.gs sources merged into one file, build constants
 *                     (BUILD_ENV, BUILD_VERSION, BUILD_COMMIT, BUILD_TIME) first,
 *                     then env.gs, then the rest. Apps Script files share one
 *                     global scope, so one file behaves exactly like many; it is
 *                     just easier to paste, diff and review in the editor.
 *                     --separate keeps one file per source plus build.gs instead.
 *   - appsscript.json the manifest from Appscript.json with the add-on name set
 *                     for the environment and urlFetchWhitelist regenerated from
 *                     env.gs so code and manifest cannot drift
 *   - .clasp.json     when a script id is known (SCRIPT_ID_<ENV> env var or
 *                     clasp.targets.json), so `clasp push` works from dist/<env>
 */
"use strict";
const fs = require("fs");
const path = require("path");
const vm = require("vm");
const { execSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..");
const MANIFEST_TEMPLATE = path.join(ROOT, "Appscript.json");
const ADDON_NAMES = { prod: "CyberNut Reporting Tool", dev: "Cybernut Dev" };

const args = process.argv.slice(2);
const separate = args.includes("--separate");
const target = (args.find((a) => !a.startsWith("--")) || "").toLowerCase();
if (!ADDON_NAMES[target]) {
  console.error("usage: node scripts/build.js dev|prod [--separate]");
  process.exit(2);
}

/** Load order for the merged file: config first, then whatever depends on it. */
const SOURCE_ORDER = ["env.gs", "languageApi.gs", "i18n.gs", "code.gs"];

/** Load env.gs in a sandbox and return its exports we need. */
function loadEnv() {
  const sandbox = { console: { log() {}, warn() {} } };
  vm.createContext(sandbox);
  vm.runInContext(fs.readFileSync(path.join(ROOT, "env.gs"), "utf8"), sandbox, { filename: "env.gs" });
  return sandbox;
}

function git(cmd, fallback) {
  try { return execSync(`git ${cmd}`, { cwd: ROOT, stdio: ["ignore", "pipe", "ignore"] }).toString().trim(); }
  catch { return fallback; }
}

function scriptIdFor(env) {
  const fromEnv = process.env[`SCRIPT_ID_${env.toUpperCase()}`];
  if (fromEnv) return fromEnv;
  const file = path.join(ROOT, "clasp.targets.json");
  if (fs.existsSync(file)) {
    const targets = JSON.parse(fs.readFileSync(file, "utf8"));
    if (targets[env] && targets[env].scriptId) return targets[env].scriptId;
  }
  return null;
}

const envModule = loadEnv();
if (!envModule.ENVIRONMENTS[target]) {
  console.error(`env.gs has no ENVIRONMENTS.${target}`);
  process.exit(2);
}

const out = path.join(ROOT, "dist", target);
fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });

// 1. sources, in load order (known ones first, any new file after, alphabetically)
const found = fs.readdirSync(ROOT).filter((f) => f.endsWith(".gs")).sort();
const sources = [...SOURCE_ORDER.filter((f) => found.includes(f)), ...found.filter((f) => !SOURCE_ORDER.includes(f))];

// 2. build constants
const version = (fs.readFileSync(path.join(ROOT, "code.gs"), "utf8").match(/var version = "([^"]+)"/) || [])[1] || "unknown";
const build = {
  BUILD_ENV: target,
  BUILD_VERSION: version,
  BUILD_COMMIT: git("rev-parse --short HEAD", "unknown"),
  BUILD_BRANCH: git("rev-parse --abbrev-ref HEAD", "unknown"),
  BUILD_TIME: new Date().toISOString(),
};
const buildSource =
  "/** Generated by scripts/build.js - do not edit. Selects the environment at build time. */\n" +
  Object.entries(build).map(([k, v]) => `var ${k} = ${JSON.stringify(v)};`).join("\n") + "\n";

let written;
if (separate) {
  for (const f of sources) fs.copyFileSync(path.join(ROOT, f), path.join(out, f));
  fs.writeFileSync(path.join(out, "build.gs"), buildSource);
  written = [...sources, "build.gs"];
} else {
  const banner = (title) => `\n\n// ${"=".repeat(74)}\n// ${title}\n// ${"=".repeat(74)}\n\n`;
  const merged =
    `// CyberNut Reporting Tool - ${target} build ${build.BUILD_VERSION} (${build.BUILD_COMMIT}, ${build.BUILD_TIME})\n` +
    `// Generated by scripts/build.js from ${sources.join(", ")} - edit the sources, not this file.\n\n` +
    buildSource +
    sources.map((f) => banner(f) + fs.readFileSync(path.join(ROOT, f), "utf8").replace(/\s+$/, "") + "\n").join("");
  // The merge must parse as one script: a duplicate top-level `let`/`const`
  // or a stray token would otherwise only surface after clasp push.
  try {
    new vm.Script(merged, { filename: "Code.gs" });
  } catch (err) {
    console.error(`merged Code.gs does not parse: ${err.message}`);
    process.exit(1);
  }
  fs.writeFileSync(path.join(out, "Code.gs"), merged);
  written = ["Code.gs"];
}

// 3. manifest
const manifest = JSON.parse(fs.readFileSync(MANIFEST_TEMPLATE, "utf8"));
manifest.addOns.common.name = ADDON_NAMES[target];
const passthrough = (manifest.urlFetchWhitelist || []).filter((u) => !/execute-api|cybernut\.ai/.test(u));
manifest.urlFetchWhitelist = [...envModule.environmentFetchPrefixes(target), ...passthrough];
fs.writeFileSync(path.join(out, "appsscript.json"), JSON.stringify(manifest, null, 2) + "\n");

// 4. clasp project file
const scriptId = scriptIdFor(target);
if (scriptId) {
  fs.writeFileSync(path.join(out, ".clasp.json"), JSON.stringify({ scriptId, rootDir: "." }, null, 2) + "\n");
}

console.log(`built ${target} -> ${path.relative(ROOT, out)}/`);
console.log(`  files     : ${[...written, "appsscript.json", scriptId ? ".clasp.json" : "(no .clasp.json: set SCRIPT_ID_" + target.toUpperCase() + " or clasp.targets.json)"].join(", ")}`);
if (!separate) console.log(`  merged    : ${sources.join(" -> ")}`);
console.log(`  name      : ${manifest.addOns.common.name}`);
console.log(`  whitelist : ${manifest.urlFetchWhitelist.length} prefixes`);
console.log(`  build     : ${build.BUILD_VERSION} ${build.BUILD_COMMIT} (${build.BUILD_BRANCH})`);
